### ISSUE TITLE
[Feature Request] Command for the list of available images

### ISSUE THREAD

**Issue by wwiiiii** [RUN-KAIST/jjalbot#16]
업로드한 이모지의 이름을 모두 외우기가 힘들기 때문에
* `/jjallist` 등의 커맨드를 통해서 전체 이모지의 이름을 확인하거나
* `/jjallist substr` 등의 커맨드를 통해 이름에 `substr`이 들어가는 이모지의 목록을 확인
할 수 있으면 좋을 것 같습니다!

**Comment by joonhyungshin** [comment]
#19 구현 완료!
